server:
    port: 8080


spring:
    sql:
        init:
            schema-locations: classpath:/db/schema.sql
            data-locations: classpath:/db/data.sql
            mode: always
    application:
        name: Virtual Learning Platform
    datasource:
        url: jdbc:mysql://localhost:3306/vlp?createDatabaseIfNotExist=true
        username: vlp
        password: vlpdbpassword
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        open-in-view: false
        hibernate:
            ddl-auto: validate
        properties:
          hibernate:
              format_sql: true
    security:
        user:
            name: test
            password: test
    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB
logging:
    level:
        org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR
jwt:
    secret: VyadmL2nJy0WIlXvH5gKBM3ZhDGPGIdDr8tZ+tQFynY= # 256-bit (32byte) in Base64 encoding --> openssl rand -base64 32
    access-token-expiration: 3600000 # 1h
    refresh-token-expiration: 86400000 #24h
user:
    profile:
        image:
            upload-dir: usersProfileImages
    course:
        image:
            upload-dir: userCourseImages
        lecture:
            assignment:
                upload-dir: userAssignments
