spring:
  autoconfigure:
    exclude: org.javers.spring.boot.sql.JaversSqlAutoConfiguration
javers:
  newObjectSnapshot: true
  objectAccessHook: org.javers.hibernate.integration.HibernateUnproxyObjectAccessHook
  sql:
    enabled: false
  redis:
    enabled: true
    audit-duration: 2h
    jedis:
      host: localhost
      port: 6379
      database: 0