server:
    port: 8080
management:
    server:
        port: 8081
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
          show-details: always
spring:
    sql:
        init:
            schema-locations: classpath:/db/schema.sql
            data-locations: classpath:/db/data.sql
            mode: always
    application:
        name: Virtual Learning Platform
    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/vlp?createDatabaseIfNotExist=true}
        username: ${SPRING_DATASOURCE_USERNAME:vlp}
        password: ${SPRING_DATASOURCE_PASSWORD:vlpdbpassword}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: false
        open-in-view: false
        hibernate:
            ddl-auto: validate
        properties:
          hibernate:
              format_sql: true
    security:
        user:
            name: test
            password: test
    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB
logging:
    level:
        org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR
jwt:
    secret: VyadmL2nJy0WIlXvH5gKBM3ZhDGPGIdDr8tZ+tQFynY= # 256-bit (32byte) in Base64 encoding --> openssl rand -base64 32
    access-token-expiration: 3600000 # 1h
    refresh-token-expiration: 86400000 #24h
user:
    profile:
        image:
            upload-dir: usersProfileImages
    course:
        image:
            upload-dir: userCourseImages
        lecture:
            assignment:
                upload-dir: userAssignments
javers:
    newObjectSnapshot: true
    auditableAspectEnabled: true
    springDataAuditableRepositoryAspectEnabled: true
    redis:
        enabled: false